services:
  postgres:
    container_name: postgres.t3-super-turbo_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_DATABASE:-t3-super-turbo}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin.t3-super-turbo_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    depends_on:
      - postgres

  message_broker:
    container_name: rabbitmq.jobs_seeker_container
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - main_network
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  cronjobs_service:
    container_name: cronjobs.jobs_seeker_container
    environment:
      DATABASE_URL: ${DB_DATABASE:-postgres://root:1234@localhost/jobs_seeker}
      MESSAGE_BROKER_HOST: ${MESSAGE_BROKER_HOST:-localhost}
      MESSAGE_BROKER_USER: ${MESSAGE_BROKER_USER:-guest}
      MESSAGE_BROKER_PASSWORD: ${MESSAGE_BROKER_PASSWORD:-guest}
      MESSAGE_BROKER_PROTOCOL: ${MESSAGE_BROKER_PROTOCOL:-amqp}
    build:
      context: .
      dockerfile: ./apps/cronjobs/Dockerfile
    restart: unless-stopped
    networks:
      - main_network

  scraper_service:
    container_name: scraper.jobs_seeker_container
    environment:
      DATABASE_URL: ${DB_DATABASE:-postgres://root:1234@localhost/jobs_seeker}
      MESSAGE_BROKER_HOST: ${MESSAGE_BROKER_HOST:-localhost}
      MESSAGE_BROKER_USER: ${MESSAGE_BROKER_USER:-guest}
      MESSAGE_BROKER_PASSWORD: ${MESSAGE_BROKER_PASSWORD:-guest}
      MESSAGE_BROKER_PROTOCOL: ${MESSAGE_BROKER_PROTOCOL:-amqp}
    build:
      context: .
      dockerfile: apps/scraper/Dockerfile
    restart: unless-stopped
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
