/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconAntDesignSkinOutlined: typeof import('~icons/ant-design/skin-outlined.jsx')['default']
  const IconCarbonAdd: typeof import('~icons/carbon/add.jsx')['default']
  const IconCarbonChevronLeft: typeof import('~icons/carbon/chevron-left.jsx')['default']
  const IconCarbonChevronRight: typeof import('~icons/carbon/chevron-right.jsx')['default']
  const IconCarbonDashboard: typeof import('~icons/carbon/dashboard.jsx')['default']
  const IconCarbonDb2Database: typeof import('~icons/carbon/db2-database.jsx')['default']
  const IconCarbonLanguage: typeof import('~icons/carbon/language.jsx')['default']
  const IconCarbonLink: typeof import('~icons/carbon/link.jsx')['default']
  const IconCarbonSearch: typeof import('~icons/carbon/search.jsx')['default']
  const IconCarbonSkillLevel: typeof import('~icons/carbon/skill-level.jsx')['default']
  const IconCarbonUserAvatar: typeof import('~icons/carbon/user-avatar.jsx')['default']
  const IconGameIconsWinchesterRifle: typeof import('~icons/game-icons/winchester-rifle.jsx')['default']
}
