/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconCarbonAdd: typeof import('~icons/carbon/add.jsx')['default']
  const IconCarbonLanguage: typeof import('~icons/carbon/language.jsx')['default']
  const IconCarbonSearch: typeof import('~icons/carbon/search.jsx')['default']
}
